export const DATE_FORMAT = {
  BASIC_FORMAT: 'YYYY-MM-DD',
  YEAR_MONTH_FORMAT: 'YYYY-MM',
  TITLE_FORMAT: 'YYYY년 MM월',
  TITLE_FORMAT_EN: 'MMMM, YYYY',
  MODAL_TITLE_FORMAT: 'M월 D일 ddd',
  MODAL_TITLE_FORMAT_EN: 'MMMM D, ddd',
};
