name: 🧪 E2E-Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
        env:
          API_DOMAIN: ${{ secrets.API_DOMAIN }}
          GUEST_ID: ${{ secrets.GUEST_ID }}
          GUEST_PW: ${{ secrets.GUEST_PW }}